version: "3.8"

services:
  habit-tracker-backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  habit-tracker-frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    restart: unless-stopped


